image: registry.gitlab.com/popadevs/gabi-store:latest

services:
  - mysql:5.7
cache:
  paths:
    - node_modules
    - .yarn
    - vendor

stages:
  - connect
  - test

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: magazin_test
  MYSQL_ROOT_PASSWORD: root

phpunit:
  stage: test
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn --version
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn install && yarn build

    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - php bin/phpunit --testsuite=unit,integration,functional --no-coverage
