services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: store-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
    depends_on:
      - php
      - database

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: store-php
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'mysql:8.0'
    container_name: store-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store
    volumes:
      - .:/app
      - ./var/data:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5

  redis:
    platform: linux/x86_64
    image: redis:latest
    container_name: store-redis
    ports:
      - "6379:6379"
